name: e_health_doctor
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.0
  go_router: ^6.4.1
  animations: ^2.0.7
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.4
  custom_check_box: ^0.0.4
  flutter_screenutil: ^5.7.0
  responsive_framework: ^0.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5
  age_calculator: ^1.0.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  lottie: ^1.4.3
  awesome_dialog: ^3.0.2
  awesome_bottom_bar: ^1.2.2
  tab_container: ^2.0.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^21.2.4
  cupertino_icons: ^1.0.2
  flutter_table: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/